name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT


  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout action test 
      #  uses: actions/checkout@v4
      #  with: 
      #    ref: 'feature/kiki'

      - name: actions/setup-node@v4
        uses: actions/setup-node@v4
      - name: npm ci
        run: npm ci 
      - name: npm run build
        run: npm run build
