---
name: Build & Test
description: Build & test
  
inputs:
  working-directory:
  required: false
  type: string
  default: '.'

runs: ubuntu-latest
steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: npm ci && npm run build
    run: npm ci && npm run build
 
