name: Build & Test
description: Build & Test
runs:
  using: "composite"
  steps:
    - name: Checkout action test 
      uses: actions/checkout@v4
      with: 
        ref:  "${{ github.ref }}"
    - name: actions/setup-node@v4
      uses: actions/setup-node@v4
    - name: npm ci
      run: npm ci 
      shell: bash
    - name: npm run build
      run: npm run build
      shell: bash
    - name: npm start
      run: npm start
      shell: bash

