name: CI/CD Pipeline

# Déclenchement du workflow
on:
  release:
    types: [published]  # Déclenché lorsqu'une nouvelle release est publiée
  push:
    branches:
      - main            # Déclenché lors d'un push (merge) sur la branche main
      - 'feature/*'     # Déclenché lors d'un push sur les branches feature/*
  workflow_dispatch:
  
jobs:
  # Job pour une nouvelle release
  release:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
              
      - name: Build and release
        run: |
          echo "Building and releasing..."
          # Ajoutez ici les commandes nécessaires pour votre job release
          # Par exemple, publier une image Docker, envoyer à un registry, etc.

      #- name: Use local hello-world-action
      #uses: ./.github/actions/npm-ci      
      #uses: ./.github/workflows/action2.yml     
           


  # Job pour la branche main
  main:
    uses: ./.github/workflows/stock-org-ci.yml
    name: Master npm cu 
    #if: github.ref == 'refs/heads/main'

     


  # Job pour les branches feature/*
  feature:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          ref: 'feature/kiki'
      - name: Build and test feature branch
        run: |
          echo "Building and testing feature branch..."
          # Ajoutez ici les commandes nécessaires pour tester ou prévisualiser la fonctionnalité

      - name: Use local ci-cd -action on feature
        #uses: ./.github/actions/npm-ci
        uses: ./.github/workflows/ci-cd
