name: docker build

on:
  push:
    paths:
      - Dockerfile*
      - .github/workflows/docker-build.yml
  workflow_dispatch:
 
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"

      - name: Every time
        run: echo "This step will always run"

      - name: sparse-checkout Dockerfile(*) 
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
            package.json
            package-lock.json                      
      
      - name: Build docker images
        id: build-image
        run: | 
          echo ---Building images and starting up docker---
          docker build -t fabstock2/my-xterm-app-docker . 
          echo ---Containers up—

  
