name: Stock Organization CI

on:
  workflow_call:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       
      - run: echo $default-branch "${{ github.ref }}"

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Run a one-line script
        run: echo Hello from Stock Organization      
      
      - name: npm ci && npm run build 
        run:  npm ci && npm run build 
      
      #- name: npm start 
      #  run:  npm start

             
